# Generated by Django 2.1.4 on 2019-01-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_remove_basket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='title',
        ),
    ]
