# Generated by Django 2.1.4 on 2018-12-17 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181213_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 16, 23, 41, 364582, tzinfo=utc)),
        ),
    ]
