# Generated by Django 2.1.4 on 2018-12-27 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181227_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 17, 10, 55, 578169, tzinfo=utc)),
        ),
    ]
