# Generated by Django 2.1.4 on 2019-01-07 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190103_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 43, 17, 882658, tzinfo=utc)),
        ),
    ]
