# Generated by Django 2.1.4 on 2018-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181213_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default='M', max_length=1, verbose_name='gender'),
        ),
    ]
