# Generated by Django 2.1.4 on 2019-01-07 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('status', models.CharField(choices=[('FM', 'forming'), ('STP', 'send to proceed'), ('PD', 'paid'), ('PRD', 'proceeded'), ('RDY', 'ready'), ('CNC', 'cancel')], default='FM', max_length=3, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ordersapp.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
